name: Main branch CI

on:
  push:
    branches:
      - '**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  JUJU_CA_CERT: ${{ secrets.JUJU_CA_CERT }}
  JUJU_CONTROLLER_ADDRESSES: ${{ secrets.JUJU_CONTROLLER_ADDRESSES }}
  JUJU_PASSWORD: ${{ secrets.JUJU_PASSWORD }}
  JUJU_USERNAME: ${{ secrets.JUJU_USERNAME }}

jobs:
  infrastructure-apply:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform init
        run: |
          cd infrastructure
          terraform init
      - id: plan
        name: Terraform plan
        run: |
          cd infrastructure
          terraform plan -no-color
      - id: apply
        name: Terraform apply
        run: |
          cd infrastructure
          terraform apply --auto-approve -no-color
  juju_deployment-apply:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform init
        run: |
          cd juju_deployment
          terraform init
      - id: plan
        name: Terraform plan
        run: |
          cd juju_deployment
          terraform plan -no-color
      - id: apply
        name: Terraform apply
        run: |
          cd juju_deployment
          terraform apply --auto-approve -no-color
